### ISSUE TITLE
download dataset?

### ISSUE THREAD

**Issue by nostorian** [sameelarif/scribe#1]
how am i supposed to download this dataset from mongodb? no documentation is provided for it.

**Comment by sameelarif** [comment]
I will upload it to Kaggle shortly and add the link to README. Haven't had time recently but it should be ready soon.

**Comment by sameelarif** [comment]
In the meantime, you can source your own data with the provided UI

**Comment by nostorian** [comment]
alright thank you so much

**Comment by nostorian** [comment]
![image](https://github.com/user-attachments/assets/d747bfa5-7d83-4d83-af46-909c67ad4766)
also @sameelarif one last question. if we increase the epochs would it result into a more smooth human like mouse movements? or the epoch count doesnt matter around here and 20 is sufficient?

**Comment by sameelarif** [comment]
@fw-real check out the README, I linked the dataset. About the epochs, I haven't ran tests to figure out the optimal number. You're free to experiment and share your findings though, I'd love to know!
