### ISSUE TITLE
js + iframe question

### ISSUE THREAD

**Issue by hallalujeh** [sameelarif/scribe#2]
Hi I really like this library, just wondering if JS support is planned anytime soon and just wanted to know if whether interacting with iframes is possible or not as it's not working for me right now

Code sample:-
```js
import puppeteer from "puppeteer";
import Scribe from "../index";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
  });
  const page = await browser.newPage();

  const scribe = new Scribe(page, {
    visualize: true,
  });

  // Set the viewport size to match the screen dimensions
  await page.setViewport({ width: 1920, height: 1080 });

  await page.goto("https://hcaptcha.projecttac.com/?sitekey=key");
  await new Promise((resolve) => setTimeout(resolve, 5000));

  await page.waitForSelector('iframe');
  const frames = await page.frames();
  let hcaptchaFrame;
  for (const frame of frames) {
      if (frame.url().includes('hcaptcha.html#frame=checkbox')) {
          hcaptchaFrame = frame;
          break;
      }
  }
  if (hcaptchaFrame) {
    await hcaptchaFrame.waitForSelector('#checkbox');
    await scribe.click('#checkbox');
  } else {
    throw new Error("hcaptchaFrame is undefined");
  }
})();
```

which throws the error:-
Error: Unable to locate element for selector: `#checkbox`

but if I remove scribe and try it with original page.click it seems to start functioning out of nowhere.

would appreciate some help.

**Comment by sameelarif** [comment]
Just added support for iframes @hallalujeh. Check out `puppeteer-scribe/examples/iframe.ts` for an example.

**Comment by sameelarif** [comment]
Note that to pass the hcaptcha though you'll still need to make your browser look more human, this alone wont be enough.

**Comment by hallalujeh** [comment]
> Note that to pass the hcaptcha though you'll still need to make your browser look more human, this alone wont be enough.

yup i am aware. i have environments ready for that. thanks for the update. i will let you know if stuff works out.
